sudo: true

language: java

jdk:
- oraclejdk8

env:
  global:
  - ENCRYPTION_LABEL: f456d91f26a4
  - COMMIT_AUTHOR_USERNAME: TravisCI
  - COMMIT_AUTHOR_EMAIL: development@dive.tv
  - TMP_DIR: "/tmp"
  - SWAGGER_CODEGEN_DIR: "/tmp/swagger-codegen"
  - SWAGGER_CODEGEN_CLI: "/tmp/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar"
  - SWAGGER_CODEGEN_TMPL_DIR: "/tmp/swagger-codegen/modules/swagger-codegen/src/main/resources"
  - SWAGGER_CODEGEN_SOURCE_DIR: "/tmp/swagger-codegen/modules/swagger-codegen/src/main/java/io/swagger/codegen/"
  - SWAGGER_CODEGEN_CONF_DIR: "/tmp/swagger-codegen/bin/touchvie"
  - SLATE_DIR: "/tmp/slate"
  - REPO_TEMPLATES_DIR: "/tmp/templates"
  - REPO_AR_LIBRARY_DIR: "/tmp/ar_library"

addons:
  apt:
    packages:
    - python3

before_install:
#- openssl aes-256-cbc -K $encrypted_23f1716b8249_key -iv $encrypted_23f1716b8249_iv -in sdk_templates_typescripy_library.enc -out sdk_templates_typescripy_library -d
- rvm install 2.2.5

install:
- ruby --version
- pip install --user awscli
- aws configure set preview.cloudfront true
- scr/install-swagger-codegen.sh
- scr/install-slate.sh
- chmod +x scr/deploy.sh scr/deploy-client.sh scr/deploy-doc.sh scr/deploy-slate-doc.sh scr/deploy-template.sh scr/git-version.sh
- scr/deploy-template.sh

script:
- scr/deploy.sh

notifications:
  email:
    - raquel.aparicio@dive.tv    
    
  on_success: never
  on_error: always
  